/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-12-10 05:49:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.vo.NoticeVO;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.ddit.vo.NoticeVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>AdminLTE 3 | Blank Page</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/css/adminlte.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar listBtn = $(\"#listBtn\");\r\n");
      out.write("\tvar formBtn = $(\"#formBtn\");\r\n");
      out.write("\t\r\n");
      out.write("\tlistBtn.on(\"click\", function(){\r\n");
      out.write("\t\tlocation.href = \"/notice/list.do\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tformBtn.on(\"click\", function(){\r\n");
      out.write("\t\tif($(\"#title\").val() == null || $(\"#title\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"제목을 입력해주세요!\");\r\n");
      out.write("\t\t\t$(\"#title\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(this).val() == \"수정\"){\r\n");
      out.write("\t\t\t$(\"#registerForm\").attr(\"action\", \"/notice/modify.do\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#registerForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<nav\r\n");
      out.write("\t\t\tclass=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-widget=\"pushmenu\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("\t\t\t<a href=\"../../index3.html\" class=\"brand-link\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/img/AdminLTELogo.png\"\r\n");
      out.write("\t\t\t\talt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\r\n");
      out.write("\t\t\t\tstyle=\"opacity: .8\"> <span\r\n");
      out.write("\t\t\t\tclass=\"brand-text font-weight-light\">SPRING</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t\t<div class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<!-- Sidebar user (optional) -->\r\n");
      out.write("\t\t\t\t<div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("\t\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/img/user2-160x160.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" class=\"d-block\">DDIT Spring</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<nav class=\"mt-2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-pills nav-sidebar flex-column\"\r\n");
      out.write("\t\t\t\t\t\tdata-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>공지사항</p>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- /.sidebar-menu -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.sidebar -->\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t\t");

			String type = "등록";
			NoticeVO noticeVO = (NoticeVO) request.getAttribute("notice");
			String status = (String) request.getAttribute("status");	// 수정일때 'u'
			if(status != null && status.equals("u")){
				type = "수정";
			}
		
      out.write("\r\n");
      out.write("\t\t<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<!-- Content Header (Page header) -->\r\n");
      out.write("\t\t\t<section class=\"content-header\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row mb-2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>공지사항 ");
      out.print(type );
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">DDIT HOME</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"breadcrumb-item active\">공지사항 ");
      out.print(type );
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				if(noticeVO != null){
			
      out.write("\r\n");
      out.write("\t\t\t<!-- Main content -->\r\n");
      out.write("\t\t\t<section class=\"content\">\r\n");
      out.write("\t\t\t\t<form class=\"row\" action=\"/notice/register.do\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("\t\t\t\t\t");

						if(status != null && status.equals("u")){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"boNo\" value=\"");
      out.print(noticeVO.getBoNo());
      out.write("\"/> \r\n");
      out.write("\t\t\t\t\t");
		
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card card-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"card-title\">공지사항 ");
      out.print(type );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-tools\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"inputName\">제목을 입력해주세요</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"title\" name=\"title\" value=\"");
      out.print(noticeVO.getTitle() );
      out.write("\" class=\"form-control\" placeholder=\"제목을 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"inputDescription\">내용을 입력해주세요</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"content\" class=\"form-control\" name=\"content\" rows=\"14\">");
      out.print(noticeVO.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"listBtn\" value=\"목록\" class=\"btn btn-success float-right\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"formBtn\" value=\"");
      out.print(type );
      out.write("\" class=\"btn btn-primary float-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t");

				}else{
			
      out.write("\r\n");
      out.write("\t\t\t<!-- Main content -->\r\n");
      out.write("\t\t\t<section class=\"content\">\r\n");
      out.write("\t\t\t\t<form class=\"row\" action=\"/notice/register.do\" method=\"post\" id=\"registerForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card card-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3 class=\"card-title\">공지사항 ");
      out.print(type );
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-tools\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"inputName\">제목을 입력해주세요</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"title\" name=\"title\" class=\"form-control\" placeholder=\"제목을 입력해주세요\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"inputDescription\">내용을 입력해주세요</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"content\" class=\"form-control\" name=\"content\" rows=\"14\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer bg-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"listBtn\" value=\"목록\" class=\"btn btn-success float-right\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"formBtn\" value=\"");
      out.print(type );
      out.write("\" class=\"btn btn-primary float-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- /.content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<footer class=\"main-footer\">\r\n");
      out.write("\t\t\t<div class=\"float-right d-none d-sm-block\">\r\n");
      out.write("\t\t\t\t<b>Version</b> 1.0.0\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<strong>Copyright &copy; 2014-2021 <a href=\"#\">DDIT\r\n");
      out.write("\t\t\t\t\tSPRING</a>.\r\n");
      out.write("\t\t\t</strong> All rights reserved.\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap 4 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<!-- AdminLTE App -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("\t<!-- AdminLTE for demo purposes -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/js/demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
