/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-12-18 09:07:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.FilesVO;
import java.util.List;
import vo.BoardCommentVO;
import vo.MemberVO;
import java.util.Map;
import vo.BoardVO;

public final class boardInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.BoardCommentVO");
    _jspx_imports_classes.add("vo.FilesVO");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("vo.BoardVO");
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>모람모람</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Roboto:wght@500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Font Stylesheet -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/style/public.css\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/public.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.serializejson.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" #boardModifyForm, #replyModifyForm { \r\n");
      out.write(" \tdisplay: none; \r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write("input idx{\r\n");
      out.write("\twidth : calc(12% - 1%);\r\n");
      out.write("\theight:\r\n");
      out.write("\tfloat : right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");


	BoardVO boardVo = (BoardVO) request.getAttribute("boardInfo");
	List<BoardCommentVO> boardCommentList = (List<BoardCommentVO>) request.getAttribute("boardCommentList");
	List<BoardCommentVO> boardReCommentList = (List<BoardCommentVO>) request.getAttribute("boardReCommentList");
	boolean isWriter = true;
	int categoryNo = (int)session.getAttribute("boardCategoryNo");
	boolean isLogin = (boolean)session.getAttribute("isLogined");
	MemberVO memberVo = null;
	Map<String, Object> loginInfo = null;
	if(isLogin){
		loginInfo = (Map<String, Object>) session.getAttribute("loginInfo");
		memberVo = (MemberVO)loginInfo.get("memberInfo");
	}

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#btnUpdate\").on(\"click\", function() {\r\n");
      out.write("\t\tvar form = document.getElementById(\"boardForm\");\r\n");
      out.write("\t\tform.method = \"GET\";\r\n");
      out.write("\t\tform.action = \"");
      out.print(request.getContextPath());
      out.write("/board/Update.do\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnDelete\").on(\"click\", function(){\r\n");
      out.write("\t\tvar form = document.getElementById(\"boardForm\");\r\n");
      out.write("\t\tform.action = \"");
      out.print(request.getContextPath());
      out.write("/board/Delete.do\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnList\").on(\"click\", function(){\r\n");
      out.write("\t\tvar form = document.getElementById(\"boardForm\");\r\n");
      out.write("\t\tform.action = \"");
      out.print(request.getContextPath());
      out.write("/board/List.do\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#addReply\").on(\"click\",function(){\r\n");
      out.write("\t\tvar form = document.getElementById(\"boardCommentForm\");\r\n");
      out.write("\t\tform.method = \"GET\";\r\n");
      out.write("\t\tform.action = \"");
      out.print(request.getContextPath());
      out.write("/board/InsertComment.do\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('.action').on('click', function(){\r\n");
      out.write("\t\t vidx =  $(this).attr('idx');\r\n");
      out.write("\t\t vname =  $(this).attr('name');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t if(vname == \"r_modify\"){  //댓글 수정 메서드\r\n");
      out.write("\t\t\tif( $('#boardModifyForm').css('display') != \"none\"){\r\n");
      out.write("\t\t    \treplyReset();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tp3tag =  $(this).parents('.p4').find('.p3');\r\n");
      out.write("\t\t\tmodicont = $(p3tag).html().trim();  //br태그가 있다 \r\n");
      out.write("\t\t\tmcont = modicont.replace(/<br>/g, \"\\n\")\r\n");
      out.write("\t\t\t$('#boardModifyForm #text').val(mcont);\r\n");
      out.write("\t\t\t$(p3tag).empty();\r\n");
      out.write("\t\t\t$(p3tag).append($('#boardModifyForm'));\r\n");
      out.write("\t\t\t$('#boardModifyForm').show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else if(vname == \"r_delete\"){\t\t// 댓글 삭제 메서드\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/board/ReplyDelete.do',\r\n");
      out.write("\t\t\t\tdata : { \"reNo\" : vidx },\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(res==\"1\"){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/MRMR/board/Read.do?board_no=");
      out.print(boardVo.getBoard_no());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#btnok').on('click', function(){\r\n");
      out.write("\t\tmodicont = $('#boardModifyForm #text').val();  //엔터가 포함 \r\n");
      out.write("\t\tmodi = modicont.replace(/\\r/g,\"\").replace(/\\n/g, \"<br>\");\r\n");
      out.write("\t\tvp3 = $('#boardModifyForm').parent();\r\n");
      out.write("\t\t$('body').append($('#boardModifyForm'));\r\n");
      out.write("\t\t$('#boardModifyForm').hide();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/board/ReplyUpdate.do',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"board_comment_no\" : vidx,\r\n");
      out.write("\t\t\t\t\"board_comment_content\" : modicont\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t$(vp3).html(modi); \r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\treplyReset = function(){\r\n");
      out.write("\t\tvp3 =  $('#boardModifyForm').parent();\r\n");
      out.write("\t\t$('body').append($('#boardModifyForm'));\r\n");
      out.write("\t\t$('#boardModifyForm').hide();\r\n");
      out.write("\t\tvp3.html(modicont);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$('#btnreset').on('click', function(){\r\n");
      out.write("\t\treplyReset();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t//대대대대대대대대대대대대대대대대대댓글 글수정 편집창에서 확인버튼 클릭 \r\n");
      out.write("\t\r\n");
      out.write("\t$('.addreply').on('click', function(){\r\n");
      out.write("\t\tvidx =  $(this).attr('idx');\r\n");
      out.write("\t\tvname =  $(this).attr('name');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(vname == \"r_add\"){  //대댓글 추가 \r\n");
      out.write("\t\t\tif( $('#replyModifyForm').css('display') != \"none\"){\r\n");
      out.write("\t\t    \treplyReset();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tp3tag =  $(this).parents('.p4').find('.p3');\r\n");
      out.write("\t\t\t$(p3tag).append($('#replyModifyForm'));\r\n");
      out.write("\t\t\t$('#replyModifyForm').show();\r\n");
      out.write("\t\t}else if(vname == \"r_delete\"){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/board/ReplyDelete.do',\r\n");
      out.write("\t\t\t\tdata : { \"reNo\" : vidx },\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(res==\"1\"){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"/MRMR/board/Read.do?board_no=");
      out.print(boardVo.getBoard_no());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#btnok2').on('click', function(){\r\n");
      out.write("\t\tmodicont = $('#replyModifyForm #text').val();  //엔터가 포함 \r\n");
      out.write("\t\tmodi = modicont.replace(/\\r/g,\"\").replace(/\\n/g, \"<br>\");\r\n");
      out.write("\t\tvp3 = $('#replyModifyForm').parent();\r\n");
      out.write("\t\t$('body').append($('#replyModifyForm'));\r\n");
      out.write("\t\t$('#replyModifyForm').hide()\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/board/ReplyReplyUpdate.do',\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"board_comment_no\" : vidx,\r\n");
      out.write("\t\t\t\t\"board_comment_content\" : modicont,\r\n");
      out.write("\t\t\t\t\"board_no\" : \"");
      out.print(boardVo.getBoard_no());
      out.write("\",\r\n");
      out.write("\t\t\t\t\"mem_no\" : \"");
      out.print(memberVo.getMem_no());
      out.write("\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\tif(res == 1){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"/MRMR/board/Read.do?board_no=");
      out.print(boardVo.getBoard_no());
      out.write("\"; \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\treplyreplyReset = function(){\r\n");
      out.write("\t\tvp3 =  $('#replyModifyForm').parent();\r\n");
      out.write("\t\t$('body').append($('#replyModifyForm'));\r\n");
      out.write("\t\t$('#replyModifyForm').hide();\r\n");
      out.write("\t\tvp3.html(modicont);\r\n");
      out.write("\t}\r\n");
      out.write("\t$('#btnreset2').on('click', function(){\r\n");
      out.write("\t\treplyreplyReset();\r\n");
      out.write("\t})\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- //댓글 수정 편집창 -->\r\n");
      out.write("\t<div id=\"boardModifyForm\">\r\n");
      out.write("\t\t<textarea id=\"text\" rows=\"5\" cols=\"40\"></textarea>\r\n");
      out.write("\t\t<input type=\"button\" value=\"확인\" id=\"btnok\"> <input\r\n");
      out.write("\t\t\ttype=\"button\" value=\"취소\" id=\"btnreset\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //대댓글 수정 편집창 -->\r\n");
      out.write("\t<div id=\"replyModifyForm\">\r\n");
      out.write("\t\t<textarea id=\"text\" rows=\"5\" cols=\"40\"></textarea>\r\n");
      out.write("\t\t<input type=\"button\" value=\"확인\" id=\"btnok2\"> \r\n");
      out.write("\t\t<input type=\"button\" value=\"취소\" id=\"btnreset2\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid pt-4 px-4\" style=\"width: 1000px;\">\r\n");
      out.write("\t\t<div class=\"bg-light rounded h-100 p-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form name=\"boardForm\" id=\"boardForm\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"boardVo\" name=\"boardVo\" value=\"");
      out.print(boardVo.getBoard_no());
      out.write("\"> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"memNo\" name=\"memNo\" value=\"");
      out.print(memberVo.getMem_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"boardCategoryNo\" name=\"boardCategoryNo\" value=\"");
      out.print(boardVo.getBoard_category_no());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div style=\"float: right;\">\r\n");
      out.write("\t\t\t\t");
if(isLogin){ 
					if((memberVo.getMem_no() == boardVo.getMem_no()) || memberVo.getMem_grade() == 9){
      out.write("\r\n");
      out.write("\t\t\t\t\t<input id=\"btnUpdate\" type=\"button\" class=\"btn btn-outline-primary m-2\" value=\"수정\">\r\n");
      out.write("\t\t\t\t\t<input id=\"btnDelete\" type=\"button\" class=\"btn btn-outline-primary m-2\" value=\"삭제\">\r\n");
      out.write("\t\t\t\t");
 }}
      out.write("\r\n");
      out.write("\t\t\t\t\t<input id=\"btnList\" type=\"button\" class=\"btn btn-outline-primary m-2\" value=\"목록보기\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br/><br/><br/>\r\n");
      out.write("\t\t\t\t<label for=\"floatingInput\">제목</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"floatingInput\" value=\"");
      out.print(boardVo.getBoard_title());
      out.write("\" readonly/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"floatingInput\">작성일</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"floatingInput\" value=\"");
      out.print(boardVo.getBoard_date());
      out.write("\" readonly/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"floatingInput\">작성자</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"floatingInput\" value=\"");
      out.print(boardVo.getMem_name());
      out.write("\" readonly/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"floatingInput\">조회수</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"floatingInput\" value=\"");
      out.print(boardVo.getBoard_hit());
      out.write("\" readonly/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"floatingInput\">내용</label>\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"floatingInput\" value=\"");
      out.print(boardVo.getBoard_content());
      out.write("\" readonly/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid pt-4 px-4 reply-body\" style=\"width: 1000px;\">\r\n");
      out.write("\t\t");
if (boardCommentList != null || boardCommentList.size() > 0) {
			for (BoardCommentVO boardCommentVO : boardCommentList) {
				if(boardCommentVO.getBoard_comment_parents() == 0){
      out.write("\r\n");
      out.write("\t\t<div class=\"p4\">\r\n");
      out.write("\t\t");
if (memberVo.getMem_no() == boardCommentVO.getMem_no()) {
      out.write("\r\n");
      out.write("\t\t\t<span class=\"p3\">");
      out.print(boardCommentVO.getBoard_comment_content());
      out.write("\r\n");
      out.write("\t\t\t<div  style=\"float: right;\">\r\n");
      out.write("\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type=\"button\" name=\"r_add\" class=\"btn btn-outline-primary m-2 addreply\" value=\"등록\">\r\n");
      out.write("\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type = \"button\" name=\"r_modify\" class=\"btn btn-outline-primary m-2 action\" value=\"수정\"> \r\n");
      out.write("\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type=\"button\" name=\"r_delete\" class=\"btn btn-outline-primary m-2 action\"  value=\"삭제\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</span></br></br>\r\n");
      out.write("\t\t\t");
if(boardReCommentList != null || boardCommentList.size() > 0) {
				for(BoardCommentVO boardReComment : boardReCommentList){
					if(boardReComment.getBoard_comment_parents() == boardCommentVO.getBoard_comment_no()){
      out.write("\r\n");
      out.write("\t\t\t\t\t<span class=\"p2\">└─ ");
      out.print(boardReComment.getBoard_comment_content());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type=\"button\" name=\"r_add\" class=\"btn btn-outline-primary m-2 addreply\" value=\"등록\">\r\n");
      out.write("\t\t\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type = \"button\" name=\"r_modify\" class=\"btn btn-outline-primary m-2 action\" value=\"수정\"> \r\n");
      out.write("\t\t\t\t\t<input idx=\"");
      out.print(boardCommentVO.getBoard_comment_no());
      out.write("\"  type=\"button\" name=\"r_delete\" class=\"btn btn-outline-primary m-2 action\"  value=\"삭제\"></br></br>\r\n");
      out.write("\t\t\t\t\t\t");
if(isLogin){
							if((memberVo.getMem_no() == boardCommentVO.getMem_no() || memberVo.getMem_grade() == 9)){
      out.write("\r\n");
      out.write("\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t");
}}}}}
					if(isLogin){
						if((memberVo.getMem_no() == boardCommentVO.getMem_no() || memberVo.getMem_grade() == 9)){
      out.write("\r\n");
      out.write("\t\t\t\t\t</div><hr/>\r\n");
      out.write("\t\t\t\t");
}}} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.print(boardCommentVO.getBoard_comment_content());
      out.write(" <br /> ");

				}}}} else { 
      out.write("\r\n");
      out.write("\t\t\t작성된 댓글이 없습니다.\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
if(isLogin){
			if(categoryNo !=1){
      out.write("\r\n");
      out.write("\t\t\t<form name=\"modifyForm\" id=\"boardCommentForm\">\r\n");
      out.write("\t\t\t\t<div class=\"form-floating mb-3\" id=\"modifyForm\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"boardVo\" name=\"boardVo\" value=\"");
      out.print(boardVo.getBoard_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t <input type=\"hidden\" id=\"memNo\" name=\"memNo\" value=\"");
      out.print(memberVo.getMem_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<textarea cols=\"110\" rows=\"3\" name=\"content\" id=\"text\"></textarea>\r\n");
      out.write("\t\t\t\t\t<button id=\"addReply\" class=\"btn btn-primary rounded-pill m-2\">댓글등록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t");
 }}
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
