/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-12-18 08:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.service;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import java.util.Map;
import vo.ServiceVO;
import java.util.List;

public final class serviceMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.ServiceVO");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>MORAM MORAM</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");

	Map<String, Object> loginInfo = (Map<String, Object>) session.getAttribute("loginInfo");
	MemberVO memberVo = (MemberVO)loginInfo.get("memberInfo");
	int memNo = memberVo.getMem_no();

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../serviceSidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-xxl position-relative bg-white d-flex p-0\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Start -->\r\n");
      out.write("        <div class=\"content col-sm-1 w-85 mx-3\">\r\n");
      out.write("            <div class=\"container-fixed pt-4 px-4 container-center-align\">\r\n");
      out.write("                <div class=\"bg-light text-center rounded p-4\" style=\"width: 1300px;\">\r\n");
      out.write("               <div class=\"main-panel\">\r\n");
      out.write("                       <div class=\"content-wrapper\">\r\n");
      out.write("                         <div class=\"row\">\r\n");
      out.write("                           <div class=\"col-xl grid-margin stretch-card\">\r\n");
      out.write("                             <div class=\"card\">\r\n");
      out.write("                               <div class=\"card-body border-bottom\">\r\n");
      out.write("                                 <div class=\"d-flex justify-content-between align-items-center flex-wrap\">\r\n");
      out.write("                                   <h3 class=\"mb-2 mb-md-0 text-uppercase font-weight-medium\">Service List</h3>\r\n");
      out.write("                                   \r\n");
      out.write("                                    <div class=\"dropdown\">\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                     <button class=\"btn bg-white p-0 pb-1 text-muted btn-sm dropdown-toggle\" type=\"button\" id=\"dropdownMenuSizeButton3\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                               카테고리 선택\r\n");
      out.write("                                     </button>\r\n");
      out.write("                                     <button class=\"btn bg-white p-0 pb-1 text-muted btn-sm dropdown-toggle\" type=\"button\" id=\"dropdownMenuSizeButton4\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                               옵션 선택\r\n");
      out.write("                                     </button>\r\n");
      out.write("                                     <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuSizeButton3\">\r\n");
      out.write("                                       <h6 class=\"dropdown-header\">Settings</h6>\r\n");
      out.write("                                       <a class=\"dropdown-item\" href=\"javascript:;\">Action</a>\r\n");
      out.write("                                       <a class=\"dropdown-item\" href=\"javascript:;\">Another action</a>\r\n");
      out.write("                                       <a class=\"dropdown-item\" href=\"javascript:;\">Something else here</a>\r\n");
      out.write("                                       <div class=\"dropdown-divider\"></div>\r\n");
      out.write("                                       <a class=\"dropdown-item\" href=\"javascript:;\">Separated link</a>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   \r\n");
      out.write("                                 </div>\r\n");
      out.write("                               </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                               ");
  
                              List<ServiceVO> serviceList = (List<ServiceVO>)request.getAttribute("serviceList");
                              List<ServiceVO> serviceSubList = (List<ServiceVO>)request.getAttribute("serviceSubList");
                           
      out.write("\r\n");
      out.write("                             <div class=\"card\">\r\n");
      out.write("                               <div class=\"card-body border-bottom\">\r\n");
      out.write("                                  <div>\r\n");
      out.write("                                     ");

                                    if(serviceList==null || serviceList.size()==0){
                                       for(ServiceVO serviceVO : serviceSubList){
                                 
      out.write("      \r\n");
      out.write("                                       <div id=\"serviceContent1\" style=\"background:gray; width : 200px;\">\r\n");
      out.write("                                          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/image/배너 (1).png\"></a>\r\n");
      out.write("                                          <p><a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write('"');
      out.write('>');
      out.print( serviceVO.getService_name() );
      out.write("</a></p>\r\n");
      out.write("                                          <p><a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write('"');
      out.write('>');
      out.print( serviceVO.getService_price() );
      out.write("</a></p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                 ");

                                       }
                                    }else{
                                       for(ServiceVO serviceVO : serviceList){
                                 
      out.write("      \r\n");
      out.write("                                       <div id=\"serviceContent2\" style=\"background:gray; width : 200px;\">\r\n");
      out.write("                                          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write("\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/image/배너 (1).png\"></a>\r\n");
      out.write("                                          <p><a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write('"');
      out.write('>');
      out.print( serviceVO.getService_name() );
      out.write("</a></p>\r\n");
      out.write("                                          <p><a href=\"");
      out.print( request.getContextPath() );
      out.write("/service/serviceDetail.do?serviceNo=");
      out.print( serviceVO.getService_no());
      out.write("&memNo=");
      out.print(memNo );
      out.write('"');
      out.write('>');
      out.print( serviceVO.getService_price() );
      out.write("</a></p>\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                 ");

                                       }
                                    }
                                 
      out.write("   \r\n");
      out.write("                                  </div>\r\n");
      out.write("                               </div>\r\n");
      out.write("                               </div>\r\n");
      out.write("                              </div>   \r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t               </div>                       \r\n");
      out.write("\t              </div>\r\n");
      out.write("\t           </div>\r\n");
      out.write("   \r\n");
      out.write("           <!-- Back to Top -->\r\n");
      out.write("           <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\" style=\"width: 50px;\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("               <!-- Right Sidebar Start -->\r\n");
      out.write("            <div class=\"bg-light fly\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"navbar-brand mx-4 mb-3\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"navbar-nav\">\r\n");
      out.write("                    <a href=\"index.jsp\" class=\"nav-item nav-link active\"><button type=\"button\" class=\"btn btn-outline-primary m-2\"><i class=\"fa fa-home me-2\"></i>My Menu</button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("\t\t            <div class=\"col-sm grid-margin stretch-card\">\r\n");
      out.write("\t\t              <div>\r\n");
      out.write("\t\t                <div class=\"card-body border-bottom\">\r\n");
      out.write("\t\t                  <div class=\"d-flex justify-content-between align-items-center flex-wrap\">\r\n");
      out.write("\t\t                    <h6 class=\"mb-2 mb-md-0 text-uppercase font-weight-medium\">추천 전문가</h6>\r\n");
      out.write("\t\t                  </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"card-body\" style=\"text-align:left\">\r\n");
      out.write("\t\t                \t<div><b>추천 서비스</b></div><br>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<hr/>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"card-body border-bottom\">\r\n");
      out.write("\t\t                  <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"OrderSummary__main\" style=\"text-align:left\">\r\n");
      out.write("\t\t\t\t\t\t<!-- divider -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"OrderSummary__divider\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t            </div><!-- div class=row end -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Right Sidebar End -->\r\n");
      out.write("            \r\n");
      out.write("     </div>\r\n");
      out.write(" \t<!-- \tfooter.jsp include -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/chart/chart.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
