/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-12-28 13:31:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672060374356L));
    _jspx_dependants.put("jar:file:/C:/Users/seolah/Documents/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MYBOARD/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"main-footer\">\r\n");
      out.write("\t<div class=\"pull-right hidden-xs\">\r\n");
      out.write("\t\t<b>Version</b> 2.4.0\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<strong>Copyright &copy; 2014-2016 <a href=\"https://adminlte.io\">Almsaeed Studio</a>. </strong> All rights reserved.\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- <div class=\"box\"> -->\r\n");
      out.write("<!-- \t<div class=\"box-header\"> -->\r\n");
      out.write("<!-- \t\t<h3 class=\"box-title\">Hover Data Table</h3> -->\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("<!-- \t<!-- /.box-header --> -->\r\n");
      out.write("<!-- \t<div class=\"box-body\"> -->\r\n");
      out.write("<!-- \t\t<div id=\"example2_wrapper\" -->\r\n");
      out.write("<!-- \t\t\tclass=\"dataTables_wrapper form-inline dt-bootstrap\"> -->\r\n");
      out.write("<!-- \t\t\t<div class=\"row\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"col-sm-6\"></div> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"col-sm-6\"></div> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t<div class=\"row\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"col-sm-12\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<table id=\"example2\" class=\"table table-bordered table-hover dataTable\" role=\"grid\" aria-describedby=\"example2_info\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t</table> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t<div class=\"row\"> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"col-sm-5\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"dataTables_info\" id=\"example2_info\" role=\"status\" aria-live=\"polite\">Showing 1 to 10 of 57 entries</div> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t<div class=\"col-sm-7\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<div class=\"dataTables_paginate paging_simple_numbers\" id=\"example2_paginate\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<ul class=\"pagination\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button previous disabled\" id=\"example2_previous\"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"0\" tabindex=\"0\">Previous</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button active\"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"1\" tabindex=\"0\">1</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"2\" tabindex=\"0\">2</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"3\" tabindex=\"0\">3</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"4\" tabindex=\"0\">4</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"5\" tabindex=\"0\">5</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button \"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"6\" tabindex=\"0\">6</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<li class=\"paginate_button next\" id=\"example2_next\"><a href=\"#\" aria-controls=\"example2\" data-dt-idx=\"7\" tabindex=\"0\">Next</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t\t</div> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("<!-- \t<!-- /.box-body --> -->\r\n");
      out.write("<!-- </div> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
