/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-12-18 08:51:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import java.util.Map;

public final class memberSidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");

Map<String, Object> loginInfo = (Map<String, Object>)session.getAttribute("loginInfo");
MemberVO loginMemberInfo = (MemberVO)loginInfo.get("memberInfo");

int grade = loginMemberInfo.getMem_grade();
String gradeName = "";
String toggleBtn = "";
if(grade == 0){
	gradeName = "일반회원";
	toggleBtn = "전문가";
}else if(grade == 1){
	gradeName = "전문가";
	toggleBtn = "일반회원";
}else if(grade == 9){
	gradeName = "관리자";
}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#withdrawal\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"ㄹㅇ 탈퇴??\")){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/withdrawal.do?mem_no=");
      out.print(loginMemberInfo.getMem_no());
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#toggle\").on(\"click\", function(){\r\n");
      out.write("\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/member/toggle.do\";\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#updateMemberInfo\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberInfo.do\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(updateMemberForm){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(updateMemberForm);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#enrollExpert\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/enrollExpert.do\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(enrollExpertForm){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(enrollExpertForm);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#chat\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/chat/main.do\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(chat){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(chat);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#myBoard\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/myBoard.do?mem_no=");
      out.print(loginMemberInfo.getMem_no());
      out.write("&page=1\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(myBoard){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(myBoard);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#schedule\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/schedule.do?mem_no=");
      out.print(loginMemberInfo.getMem_no());
      out.write("\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(schedule){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(schedule);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#serviceHistory\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/serviceHistory.do?mem_no=");
      out.print(loginMemberInfo.getMem_no());
      out.write("&page=1\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(serviceHistory){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(serviceHistory);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#wishlist\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/member/wishlist.do?mem_no=");
      out.print(loginMemberInfo.getMem_no());
      out.write("\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tsuccess : function(wishlist){\r\n");
      out.write("\t\t\t\t$(\"#myPageDiv\").html(wishlist);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\talert(\"상태 : \" + xhr.status);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType : \"html\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//----------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#serviceInsert').on(\"click\",function(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.print( request.getContextPath());
      out.write("/view/service/serviceInsert.jsp\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//내 서비스 리스트 \r\n");
      out.write("\t\t$('#myServiceList').on('click',function(){\r\n");
      out.write("\t\t\tmyservicelist();\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmyservicelist = function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print( request.getContextPath());
      out.write("/service/myServiceList.do',\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t\t\tdata : { \"memNo\" : '25' },\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tcode=\"\";\r\n");
      out.write("\t\t\t\t$.each(res,function(i,v){\r\n");
      out.write("\t\t\t\t\tcode += \"<a href='");
      out.print( request.getContextPath());
      out.write("/service/serviceDetail.do?serviceNo=\" + v.service_no +\"' 서비스디테일\";\r\n");
      out.write("\t\t\t\t\tcode += \"<p>서비스 번호:\"+ v.service_no +\"[서비스이름:]\"+v.service_name+\"[서비스가격:]\"+v.service_price+\"</p></a>\";\r\n");
      out.write("\t  \t\t\t\tcode += \"<button type='button' id='serviceDelete' value='\"+v.service_no+\"'>서비스삭제</button>\"; \r\n");
      out.write("\t  \t\t\t\tcode += \"<br>\";\r\n");
      out.write("\t \t\t\t\tcode += \"<button type='button' id='serviceUpdate' value='\"+v.service_no+\"'>서비스수정</button>\";\r\n");
      out.write("\t  \t\t\t\tcode += v.service_no; \r\n");
      out.write("\t  \t\t\t\tcode += \"<br>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t })\r\n");
      out.write("\t\t\t\t\t$('#myservice').html(code);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태\" + xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//서비스삭제\r\n");
      out.write("\t\t$(document).on('click','#serviceDelete',function(){\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t\t\tval = $(this).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(val);\r\n");
      out.write("\t \t\t \t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print( request.getContextPath());
      out.write("/service/serviceDelete.do',\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tdata : { \"serviceNo\" : val },\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(res=='1'){\r\n");
      out.write("\t\t\t\t\t\talert('삭제가 완료되었습니다.');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tmyservicelist();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태\" + xhr.status);\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'text'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}) //서비스삭제끝\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//서비스 수정\r\n");
      out.write("\t \t$(document).on('click','#serviceUpdate',function(){\r\n");
      out.write("\t\t\tval = $(this).val();\r\n");
      out.write("\t\t\tlocation.href= '");
      out.print( request.getContextPath() );
      out.write("/service/serviceUpdate.do?serviceNo='+ val;\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\t\r\n");
      out.write("\t \t$('#myWishList').on('click',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print( request.getContextPath());
      out.write("/service/myWishlist.do',\r\n");
      out.write("\t\t\t\tdata : { \"memNo\" : '26' },\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tcode=\"\";\r\n");
      out.write("\t\t\t\t\tif(res!=\"찜 목록이 없습니다.\"){\r\n");
      out.write("\t\t\t\t\t\t$.each(res,function(i,v){\r\n");
      out.write("\t\t\t\t\t\t\tcode += \"<a href='");
      out.print( request.getContextPath());
      out.write("/service/serviceDetail.do?serviceNo=\" + v.service_no +\"' 서비스디테일\";\r\n");
      out.write("\t\t\t\t\t\t\tcode += \"<p>서비스 번호:\"+ v.service_no +\"[서비스이름:]\"+v.service_name+\"[서비스가격:]\"+v.service_price+\"</a>\";\r\n");
      out.write("\t\t\t  \t\t\t\tcode += \"<button type='button' id='mywishDelete' value='\"+v.service_no+\"'>찜 삭제</button></p>\"; \r\n");
      out.write("\t\t\t\t\t\t}) \r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tcode = \"<p>\"+res+\"</p>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$('#myWish').html(code);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"에러\"+xhr.status)\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'json'\r\n");
      out.write("\t\t\t}) //ajax끝\r\n");
      out.write("\t\t}) //내 위시리스트 가져오기 끝\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on('click','#mywishDelete',function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : '");
      out.print( request.getContextPath());
      out.write("/service/memWishlist.do',\r\n");
      out.write("\t\t\t\tdata : { \"countWishlist\" : \"1\" ,\r\n");
      out.write("\t\t\t\t\t\t \"memNo\" : \"26\",\r\n");
      out.write("\t\t\t\t\t\t \"serviceNo\" : $(this).val() },\r\n");
      out.write("\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\tsuccess : function(res){\r\n");
      out.write("\t\t\t\t\tif(res==1){\r\n");
      out.write("\t   \t\t\t\t\t\talert(\"성공\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\talert(\"상태 : \"+xhr.status);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : 'text'\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}) \r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"sidebar pe-4 pb-3\">\r\n");
      out.write("    <nav class=\"navbar bg-light navbar-light\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"navbar-nav w-100\" style=\"margin-left: 10%;\">\r\n");
      out.write("        <br/>\r\n");
      out.write("        <br/>\r\n");
      out.write("        <br/>\r\n");
      out.write("        \r\n");
      out.write("      ");
if("일반회원".equals(gradeName)){ 
      out.write("\r\n");
      out.write("        \t<button id=\"toggle\" name=\"toggle\" class=\"btn btn-primary w-100 m-2\" type=\"button\">⇔ ");
      out.print(toggleBtn);
      out.write(" 전환</button>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"updateMemberInfo\"><i class=\"fa fa-tachometer-alt me-2\"></i>회원 정보 변경</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"enrollExpert\"><i class=\"fa fa-tachometer-alt me-2\"></i>전문가 정보 등록</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"chat\"><i class=\"fa fa-th me-2\"></i>채팅내역</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"myBoard\"><i class=\"fa fa-keyboard me-2\"></i>작성한 게시글</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"schedule\"><i class=\"fa fa-table me-2\"></i>일정</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"serviceHistory\"><i class=\"fa fa-chart-bar me-2\"></i>이용한 서비스 내역</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"wishlist\"><i class=\"fa fa-tachometer-alt me-2\"></i>위시리스트</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"withdrawal\"><i class=\"fa fa-chart-bar me-2\"></i>회원탈퇴</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\" class=\"nav-item nav-link\"><i class=\"fa fa-keyboard me-2\"></i>로그아웃</a>\r\n");
      out.write("            \r\n");
      out.write("      ");
}else if("전문가".equals(gradeName)){ 
      out.write("\r\n");
      out.write("        \t<button id=\"toggle\" name=\"toggle\" class=\"btn btn-primary w-100 m-2\" type=\"button\">⇔ ");
      out.print(toggleBtn);
      out.write(" 전환</button>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"updateMemberInfo\"><i class=\"fa fa-tachometer-alt me-2\"></i>회원 정보 변경</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"chat\"><i class=\"fa fa-th me-2\"></i>채팅내역</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"myBoard\"><i class=\"fa fa-keyboard me-2\"></i>작성한 게시글</a>\r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"schedule\"><i class=\"fa fa-table me-2\"></i>일정</a>\r\n");
      out.write("            \r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"myServiceList\"><i class=\"fa fa-chart-bar me-2\"></i>내 서비스</a>\r\n");
      out.write("            \r\n");
      out.write("            <a class=\"nav-item nav-link\" id=\"withdrawal\"><i class=\"fa fa-chart-bar me-2\"></i>회원탈퇴</a>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\" class=\"nav-item nav-link\"><i class=\"fa fa-keyboard me-2\"></i>로그아웃</a>\r\n");
      out.write("    \r\n");
      out.write("      ");
}else if("관리자".equals(gradeName)){ 
      out.write("\r\n");
      out.write("            <div class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-th me-2\"></i>회원 관리</a>\r\n");
      out.write("                <div class=\"dropdown-menu shadow-sm m-0\">\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=1&page=1\" class=\"dropdown-item\">목록 조회</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=1&page=1\" class=\"dropdown-item\">신고내역 조회</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-th me-2\"></i>서비스 관리</a>\r\n");
      out.write("                <div class=\"dropdown-menu shadow-sm m-0\">\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=1&page=1\" class=\"dropdown-item\">결제내역 조회</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=2&page=1\" class=\"dropdown-item\">예약일정 조회</a> \r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=3&page=1\" class=\"dropdown-item\">신청/승인 관리</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=3&page=1\" class=\"dropdown-item\">카테고리 관리</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-th me-2\"></i>게시판 관리</a>\r\n");
      out.write("                <div class=\"dropdown-menu shadow-sm m-0\">\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=1&page=1\" class=\"dropdown-item\">공지사항</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=2&page=1\" class=\"dropdown-item\">문의게시판</a> \r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=3&page=1\" class=\"dropdown-item\">후기게시판</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=4&page=1\" class=\"dropdown-item\">홍보게시판</a>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/setSession.do?boardCategoryNo=5&page=1\" class=\"dropdown-item\">자유게시판</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\" class=\"nav-item nav-link\"><i class=\"fa fa-keyboard me-2\"></i>로그아웃</a>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
